# --- Build stage ---
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# --- Production stage ---
FROM nginx:alpine

# Copy Vite production build to Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Nginx already listens on 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
